services:
  eve-server:
    build:
      context: ./eve-server
      dockerfile: Dockerfile
    container_name: eve-server
    working_dir: /app
    networks:
      - eve-network

  eve-client:
    build:
      context: ./eve-client-web
      dockerfile: Dockerfile
    container_name: eve-client
    working_dir: /app
    depends_on:
      - eve-server
    networks:
      - eve-network

  db:
    image: postgres:15
    container_name: eve-postgres
    profiles:
      - local-db
    environment:
      POSTGRES_DB: eve_db
      POSTGRES_USER: eve_admin
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eve-network

networks:
  eve-network:
    driver: bridge

volumes:
  postgres-data: